# Generated by Django 4.2.30 on 2026-04-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('platform', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('developer', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('na_sales', models.FloatField(blank=True, null=True)),
                ('eu_sales', models.FloatField(blank=True, null=True)),
                ('jp_sales', models.FloatField(blank=True, null=True)),
                ('other_sales', models.FloatField(blank=True, null=True)),
                ('global_sales', models.FloatField(blank=True, null=True)),
                ('critic_score', models.FloatField(blank=True, null=True)),
                ('critic_count', models.IntegerField(blank=True, null=True)),
                ('user_score', models.FloatField(blank=True, null=True)),
                ('user_count', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, choices=[('AO', 'AO'), ('M', 'M'), ('E', 'E'), ('T', 'T'), ('E10+', 'E10+'), ('EC', 'EC'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], default='csv', max_length=50)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.publisher')),
            ],
        ),
    ]
