# Generated by Django 4.2.30 on 2026-04-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fighting', 'Fighting'), ('Platform', 'Platform'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('Role-Playing', 'Role-Playing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Unknown', 'Unknown'), ('Misc', 'Misc')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(choices=[('Nintendo', 'Nintendo'), ('Electronic Arts', 'Electronic Arts'), ('Activision', 'Activision'), ('Sony Computer Entertainment', 'Sony Computer Entertainment'), ('Ubisoft', 'Ubisoft'), ('Sega', 'Sega'), ('Bandai Namco Entertainment', 'Bandai Namco Entertainment'), ('Take-Two Interactive', 'Take-Two Interactive'), ('Capcom', 'Capcom'), ('Square Enix', 'Square Enix'), ('Konami Digital Entertainment', 'Konami Digital Entertainment'), ('Unknown', 'Unknown'), ('Other', 'Other')], max_length=200, unique=True),
        ),
    ]
